# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04549ea4c4318ea028d0203121aa7088f75e4911e7a94716f3b86a111e70f6f468c780dc3289b5f3b0e4bcdd94f0bd1776d1d9c54bbe30c14ae73eb34da55fa1

test:
  secret_key_base: 385c5c8b9d5ee2372aee4abec798e2636c87367fba84d64ac322ab853b2fe70c68077211f1623a3911d0f95d606d214e49aa799e1ed864395c3acf65f02a434b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
